-- luban 的 PostgreSQL schema（最终形态）。
--
-- 口径约定：
-- - 时间一律存 unix 秒（BIGINT），`unixepoch()` 是下面定义的同名函数，查询里照旧用它；
-- - 整数一律 BIGINT（Rust 侧统一 i64），0/1 开关列也是 BIGINT + CHECK，不用 BOOLEAN：
--   查询里大量 `SUM(flag)`、`flag = 0` 的写法照搬过来不用改；
-- - 浮点一律 DOUBLE PRECISION（Rust 侧 f64）；
-- - 自增主键一律 `GENERATED BY DEFAULT AS IDENTITY`，id 不回收（同 SQLite 的 AUTOINCREMENT）。

CREATE FUNCTION unixepoch() RETURNS BIGINT
    LANGUAGE sql STABLE
    AS $$ SELECT extract(epoch FROM now())::BIGINT $$;

-- ---------------------------------------------------------------------------
-- 成员与登录会话
-- ---------------------------------------------------------------------------

-- admin 行恒存在（还没设密码时 password_hash 为空），由启动时补上。
-- username 不区分大小写唯一：查找时一律比 lower(username)。
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT   NOT NULL,
    password_hash TEXT   NOT NULL DEFAULT '',
    role          TEXT   NOT NULL CHECK (role IN ('admin', 'viewer', 'agent', 'user')),
    parent_id     BIGINT,
    disabled      BIGINT NOT NULL DEFAULT 0 CHECK (disabled IN (0, 1)),
    created_at    BIGINT NOT NULL DEFAULT unixepoch(),
    updated_at    BIGINT NOT NULL DEFAULT unixepoch()
);
CREATE UNIQUE INDEX uq_users_username ON users (lower(username));
CREATE UNIQUE INDEX uq_users_singleton ON users (role) WHERE role IN ('admin', 'viewer');
CREATE INDEX idx_users_parent ON users (parent_id);

-- pw_tag：签发时的密码指纹（见 crate::auth::password_tag），密码一变旧会话随即失效。
CREATE TABLE sessions (
    token_hash TEXT   PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    created_at BIGINT NOT NULL DEFAULT unixepoch(),
    expires_at BIGINT NOT NULL,
    pw_tag     TEXT   NOT NULL DEFAULT ''
);
CREATE INDEX idx_sessions_user ON sessions (user_id);

-- ---------------------------------------------------------------------------
-- 账号
-- ---------------------------------------------------------------------------

-- access_token / refresh_token 存密文（见 store::secret），唯一约束挂在 refresh_token 的
-- 指纹列 refresh_token_hash 上：密文随机，对它做唯一约束形同虚设。
CREATE TABLE credentials (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label                   TEXT   NOT NULL DEFAULT '',
    tier                    TEXT,
    org_type                TEXT,
    access_token            TEXT   NOT NULL,
    refresh_token           TEXT   NOT NULL,
    expires_at              BIGINT NOT NULL,
    priority                BIGINT NOT NULL DEFAULT 2,
    disabled                BIGINT NOT NULL DEFAULT 0 CHECK (disabled IN (0, 1)),
    created_at              BIGINT NOT NULL DEFAULT unixepoch(),
    updated_at              BIGINT NOT NULL DEFAULT unixepoch(),
    -- 三态：>0 独立 / 0 跟随全局 / <0 不限。
    device_limit            BIGINT NOT NULL DEFAULT 0,
    -- 自动检测到的上游账号级错误原因；NULL = 不是被自动停用的（见 mark_banned）。
    ban_reason              TEXT,
    account_uuid            TEXT,
    -- 被上游限流自动停用后、到点自动重新启用的时刻；NULL = 不自动恢复。
    resume_at               BIGINT,
    -- 该账号专用的出站代理；NULL = 直连。
    proxy                   TEXT,
    rpm_limit               BIGINT NOT NULL DEFAULT 0,
    rate_limit_tier         TEXT,
    org_uuid                TEXT,
    subscription_created_at TEXT,
    -- NULL = 跟随全局，0 = 这一档不停，1..=100 = 独立阈值。
    quota_pause_pct         BIGINT,
    quota_pause_pct_7d      BIGINT,
    session_limit           BIGINT NOT NULL DEFAULT 0,
    org_name                TEXT,
    seat_tier               TEXT,
    subscription_status     TEXT,
    extra_usage_enabled     BIGINT,
    owner_id                BIGINT,
    refresh_token_hash      TEXT
);
CREATE INDEX idx_credentials_priority ON credentials (priority, id);
CREATE INDEX idx_credentials_owner ON credentials (owner_id);
CREATE UNIQUE INDEX uq_credentials_refresh_hash ON credentials (refresh_token_hash);

-- 不带 owner 插入的号默认挂到 admin 名下：调度只认号主存在的号，留成 NULL 就永远调度不到。
CREATE FUNCTION credentials_default_owner() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF NEW.owner_id IS NULL THEN
        NEW.owner_id := (SELECT id FROM users WHERE role = 'admin');
    END IF;
    RETURN NEW;
END
$$;
CREATE TRIGGER trg_credentials_default_owner
    BEFORE INSERT ON credentials
    FOR EACH ROW EXECUTE FUNCTION credentials_default_owner();

-- 账本：每凭证的终身累计统计与最新额度快照，与 usage_logs 的插入在同一事务内更新。
CREATE TABLE credential_stats (
    cred_id           BIGINT PRIMARY KEY,
    last_used_at      BIGINT,
    cost_total_usd    DOUBLE PRECISION NOT NULL DEFAULT 0,
    snapshot_ts       BIGINT,
    unified_status    TEXT,
    rl_5h_utilization DOUBLE PRECISION,
    rl_5h_reset       BIGINT,
    rl_7d_utilization DOUBLE PRECISION,
    rl_7d_reset       BIGINT,
    rl_representative TEXT,
    overage_in_use    BIGINT,
    -- 上游本次报告的全部窗口（JSON 数组，见 QuotaWindow）。
    windows           TEXT
);

-- 上游判成「这个号的套餐不含这个模型」的记录，见 CredentialStore::deny_model。
CREATE TABLE model_denials (
    cred_id    BIGINT NOT NULL,
    model      TEXT   NOT NULL,
    reason     TEXT   NOT NULL DEFAULT '',
    learned_at BIGINT NOT NULL DEFAULT unixepoch(),
    expires_at BIGINT,
    PRIMARY KEY (cred_id, model)
);

-- ---------------------------------------------------------------------------
-- 分组与接入 Key
-- ---------------------------------------------------------------------------

-- name 不区分大小写唯一：查找时一律比 lower(name)。
CREATE TABLE pool_groups (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT   NOT NULL,
    note       TEXT   NOT NULL DEFAULT '',
    is_default BIGINT NOT NULL DEFAULT 0 CHECK (is_default IN (0, 1)),
    created_at BIGINT NOT NULL DEFAULT unixepoch()
);
CREATE UNIQUE INDEX uq_pool_groups_name ON pool_groups (lower(name));
CREATE UNIQUE INDEX uq_pool_groups_default ON pool_groups (is_default) WHERE is_default = 1;

CREATE TABLE credential_groups (
    cred_id  BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    PRIMARY KEY (cred_id, group_id)
);
CREATE INDEX idx_credential_groups_group ON credential_groups (group_id);

-- 新插入的号先落进默认分组：上号接口随后按所选分组整体替换；直接写库的号就留在默认
-- 分组里，不会因为一个分组都不在而永远调度不到。
CREATE FUNCTION credentials_default_group() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    INSERT INTO credential_groups (cred_id, group_id)
    SELECT NEW.id, id FROM pool_groups WHERE is_default = 1
    ON CONFLICT DO NOTHING;
    RETURN NULL;
END
$$;
CREATE TRIGGER trg_credentials_default_group
    AFTER INSERT ON credentials
    FOR EACH ROW EXECUTE FUNCTION credentials_default_group();

CREATE TABLE group_grants (
    group_id BIGINT NOT NULL,
    user_id  BIGINT NOT NULL,
    PRIMARY KEY (group_id, user_id)
);
CREATE INDEX idx_group_grants_user ON group_grants (user_id);

CREATE TABLE api_keys (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label      TEXT   NOT NULL DEFAULT '',
    key_hash   TEXT   NOT NULL UNIQUE,
    key_sealed TEXT   NOT NULL,
    key_prefix TEXT   NOT NULL DEFAULT '',
    all_groups BIGINT NOT NULL DEFAULT 1 CHECK (all_groups IN (0, 1)),
    disabled   BIGINT NOT NULL DEFAULT 0 CHECK (disabled IN (0, 1)),
    created_at BIGINT NOT NULL DEFAULT unixepoch()
);

CREATE TABLE api_key_groups (
    key_id   BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    ord      BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (key_id, group_id)
);

-- ---------------------------------------------------------------------------
-- 设置与代理池
-- ---------------------------------------------------------------------------

CREATE TABLE settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- 唯一约束是「人 + 地址」：不同的人可以各存一条同样的地址。owner_id 必须非空：PG 的唯一
-- 索引里 NULL 互不相等，留空的话同一个地址可以无限重复插。
CREATE TABLE proxies (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label      TEXT   NOT NULL DEFAULT '',
    url        TEXT   NOT NULL,
    created_at BIGINT NOT NULL DEFAULT unixepoch(),
    owner_id   BIGINT NOT NULL
);
CREATE UNIQUE INDEX uq_proxies_owner_url ON proxies (owner_id, url);

-- ---------------------------------------------------------------------------
-- 设备 / 会话绑定
-- ---------------------------------------------------------------------------

-- 设备→凭证的粘性绑定：同一 device_id 始终命中同一凭证。
CREATE TABLE device_bindings (
    device_id     TEXT   PRIMARY KEY,
    cred_id       BIGINT NOT NULL,
    request_count BIGINT NOT NULL DEFAULT 0,
    created_at    BIGINT NOT NULL DEFAULT unixepoch(),
    last_seen_at  BIGINT NOT NULL DEFAULT unixepoch()
);
CREATE INDEX idx_device_bindings_cred ON device_bindings (cred_id);
CREATE INDEX idx_device_bindings_seen ON device_bindings (last_seen_at);

-- 会话→凭证的粘性绑定，并占该凭证的会话名额。键的取法见 proxy 的 session_binding_key。
-- slot：在该凭证上占的槽位（0 起；沿用来访会话 id 的记 -1）；slot_lost：休眠期间槽位已被
-- 别的会话接手；last_model / device_id：只给后台列看，不参与选号。
CREATE TABLE session_bindings (
    session_key   TEXT   PRIMARY KEY,
    cred_id       BIGINT NOT NULL,
    slot          BIGINT NOT NULL DEFAULT 0,
    request_count BIGINT NOT NULL DEFAULT 0,
    last_model    TEXT,
    slot_lost     BIGINT NOT NULL DEFAULT 0,
    created_at    BIGINT NOT NULL DEFAULT unixepoch(),
    last_seen_at  BIGINT NOT NULL DEFAULT unixepoch(),
    device_id     TEXT
);
CREATE INDEX idx_session_bindings_cred ON session_bindings (cred_id);
CREATE INDEX idx_session_bindings_seen ON session_bindings (last_seen_at);

-- 会话绑定的历史事件（store::session_events）：只在状态变化时记，保留 7 天。
CREATE TABLE session_binding_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts           BIGINT NOT NULL DEFAULT unixepoch(),
    session_key  TEXT   NOT NULL,
    event        TEXT   NOT NULL,
    cred_id      BIGINT,
    prev_cred_id BIGINT,
    slot         BIGINT,
    prev_slot    BIGINT,
    other_key    TEXT,
    idle_secs    BIGINT,
    reason       TEXT
);
CREATE INDEX idx_session_events_key ON session_binding_events (session_key, id);
CREATE INDEX idx_session_events_slot ON session_binding_events (cred_id, slot, id);
CREATE INDEX idx_session_events_prev_slot
    ON session_binding_events (prev_cred_id, prev_slot, id) WHERE prev_cred_id IS NOT NULL;
CREATE INDEX idx_session_events_ts ON session_binding_events (ts);

-- ---------------------------------------------------------------------------
-- 用量流水与账本
-- ---------------------------------------------------------------------------

-- 每次转发的用量日志，只保留近期（prune_usage_logs）。列含义见 UsageRecord / Forensics。
CREATE TABLE usage_logs (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts                    BIGINT NOT NULL DEFAULT unixepoch(),
    cred_id               BIGINT,
    cred_label            TEXT   NOT NULL DEFAULT '',
    device_id             TEXT,
    model                 TEXT,
    path                  TEXT   NOT NULL DEFAULT '',
    -- ua = 来访客户端自报的那份；ua_out = 实际发给上游的那份。
    ua                    TEXT,
    ua_out                TEXT,
    status                BIGINT NOT NULL DEFAULT 0,
    has_usage             BIGINT NOT NULL DEFAULT 0 CHECK (has_usage IN (0, 1)),
    input_tokens          BIGINT,
    output_tokens         BIGINT,
    cache_creation_tokens BIGINT,
    cache_5m_tokens       BIGINT,
    cache_1h_tokens       BIGINT,
    cache_read_tokens     BIGINT,
    ttft_ms               BIGINT,
    total_ms              BIGINT,
    unified_status        TEXT,
    rl_5h_status          TEXT,
    rl_5h_reset           BIGINT,
    rl_5h_utilization     DOUBLE PRECISION,
    rl_7d_status          TEXT,
    rl_7d_reset           BIGINT,
    rl_7d_utilization     DOUBLE PRECISION,
    rl_representative     TEXT,
    rl_overage_in_use     BIGINT,
    ratelimit_raw         TEXT,
    cost_usd              DOUBLE PRECISION,
    sse_aggregated        BIGINT NOT NULL DEFAULT 0 CHECK (sse_aggregated IN (0, 1)),
    request_id            TEXT,
    upstream_request_id   TEXT,
    proxy                 TEXT,
    simulated             BIGINT NOT NULL DEFAULT 0,
    shape                 TEXT,
    session_id            TEXT,
    error_type            TEXT,
    error_message         TEXT,
    third_party           BIGINT NOT NULL DEFAULT 0,
    rewrites              TEXT,
    device_id_out         TEXT,
    response_excerpt      TEXT,
    sim_reason            TEXT,
    session_key           TEXT,
    session_id_in         TEXT
);
CREATE INDEX idx_usage_logs_ts ON usage_logs (ts);
CREATE INDEX idx_usage_logs_device ON usage_logs (device_id, cred_id);
CREATE INDEX idx_usage_logs_cred_id ON usage_logs (cred_id, id);
CREATE INDEX idx_usage_logs_request_id ON usage_logs (request_id);
CREATE INDEX idx_usage_logs_session_key ON usage_logs (session_key, id) WHERE session_key IS NOT NULL;
CREATE INDEX idx_usage_logs_session_id ON usage_logs (session_id, id) WHERE session_id IS NOT NULL;
CREATE INDEX idx_usage_logs_session_id_in
    ON usage_logs (session_id_in, id) WHERE session_id_in IS NOT NULL;
-- 账号列表按号聚合额度窗口内的费用 / 条数 / token：覆盖索引，整段范围扫描不回表。
CREATE INDEX idx_usage_logs_cred_usage ON usage_logs (cred_id, ts)
    INCLUDE (cost_usd, input_tokens, output_tokens, cache_creation_tokens,
             cache_5m_tokens, cache_1h_tokens, cache_read_tokens);
CREATE INDEX idx_usage_logs_model_ts ON usage_logs (model, ts);

-- 设备费用账本：终身累计。不记在 device_bindings 上——绑定行会被解绑 / TTL 清掉重建。
CREATE TABLE device_costs (
    device_id     TEXT   NOT NULL,
    cred_id       BIGINT NOT NULL,
    cost_usd      DOUBLE PRECISION NOT NULL DEFAULT 0,
    request_count BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (device_id, cred_id)
);

-- 用量预聚合：15 分钟 × 维度（all / model / cred）一行，见 store::rollup。
CREATE TABLE usage_rollup (
    dim            TEXT   NOT NULL CHECK (dim IN ('all', 'model', 'cred')),
    bucket         BIGINT NOT NULL,
    key            TEXT   NOT NULL,
    label          TEXT   NOT NULL DEFAULT '',
    requests       BIGINT NOT NULL DEFAULT 0,
    input_tokens   BIGINT NOT NULL DEFAULT 0,
    cached_tokens  BIGINT NOT NULL DEFAULT 0,
    written_tokens BIGINT NOT NULL DEFAULT 0,
    saved_usd      DOUBLE PRECISION NOT NULL DEFAULT 0,
    lat_count      BIGINT NOT NULL DEFAULT 0,
    ttft_sum       BIGINT NOT NULL DEFAULT 0,
    gen_tokens     BIGINT NOT NULL DEFAULT 0,
    gen_ms         BIGINT NOT NULL DEFAULT 0,
    ttft_hist      BYTEA,
    PRIMARY KEY (dim, bucket, key)
);

-- 费用汇总：小时 × 号主 × 号 × 接入 Key × 分组 × 模型，长期保留，见 store::billing。
CREATE TABLE billing_hourly (
    hour               BIGINT NOT NULL,
    owner_id           BIGINT NOT NULL DEFAULT 0,
    cred_id            BIGINT NOT NULL,
    key_id             BIGINT NOT NULL DEFAULT 0,
    group_id           BIGINT NOT NULL DEFAULT 0,
    model              TEXT   NOT NULL DEFAULT '',
    requests           BIGINT NOT NULL DEFAULT 0,
    input_tokens       BIGINT NOT NULL DEFAULT 0,
    output_tokens      BIGINT NOT NULL DEFAULT 0,
    cache_write_tokens BIGINT NOT NULL DEFAULT 0,
    cache_read_tokens  BIGINT NOT NULL DEFAULT 0,
    cost_usd           DOUBLE PRECISION NOT NULL DEFAULT 0,
    PRIMARY KEY (hour, owner_id, cred_id, key_id, group_id, model)
);
CREATE INDEX idx_billing_owner_hour ON billing_hourly (owner_id, hour);

-- ---------------------------------------------------------------------------
-- 封号取证
-- ---------------------------------------------------------------------------

-- 封号事件：每次自动停用落一条，只追加，不随删号删除、不裁剪。列含义见 BanEvent，
-- 列表类字段（models_7d 等）存 JSON 文本。
CREATE TABLE ban_events (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts                  BIGINT NOT NULL DEFAULT unixepoch(),
    cred_id             BIGINT NOT NULL,
    cred_label          TEXT   NOT NULL DEFAULT '',
    source              TEXT   NOT NULL DEFAULT '',
    reason              TEXT   NOT NULL DEFAULT '',
    status              BIGINT,
    error_type          TEXT,
    error_message       TEXT,
    request_id          TEXT,
    upstream_request_id TEXT,
    tier                TEXT,
    org_type            TEXT,
    proxy               TEXT,
    account_created_at  BIGINT NOT NULL DEFAULT 0,
    lifetime_requests   BIGINT NOT NULL DEFAULT 0,
    lifetime_cost_usd   DOUBLE PRECISION NOT NULL DEFAULT 0,
    last_used_at        BIGINT,
    requests_7d         BIGINT NOT NULL DEFAULT 0,
    devices_7d          BIGINT NOT NULL DEFAULT 0,
    models_7d           TEXT,
    uas_7d              TEXT,
    proxies_7d          TEXT,
    last_unified_status TEXT,
    last_overage_in_use BIGINT,
    frozen_rows         BIGINT NOT NULL DEFAULT 0,
    devices_out_7d      BIGINT NOT NULL DEFAULT 0,
    device_ids_out_7d   TEXT
);
CREATE INDEX idx_ban_events_cred_ts ON ban_events (cred_id, ts);

-- 封号时冻结的流水：与 usage_logs 同列（见 USAGE_LOG_COLS），多出 ban_event_id 与原行 id。
CREATE TABLE usage_logs_frozen (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ban_event_id          BIGINT NOT NULL,
    src_id                BIGINT,
    ts                    BIGINT NOT NULL DEFAULT unixepoch(),
    cred_id               BIGINT,
    cred_label            TEXT   NOT NULL DEFAULT '',
    device_id             TEXT,
    model                 TEXT,
    path                  TEXT   NOT NULL DEFAULT '',
    ua                    TEXT,
    ua_out                TEXT,
    status                BIGINT NOT NULL DEFAULT 0,
    has_usage             BIGINT NOT NULL DEFAULT 0,
    input_tokens          BIGINT,
    output_tokens         BIGINT,
    cache_creation_tokens BIGINT,
    cache_5m_tokens       BIGINT,
    cache_1h_tokens       BIGINT,
    cache_read_tokens     BIGINT,
    ttft_ms               BIGINT,
    total_ms              BIGINT,
    unified_status        TEXT,
    rl_5h_status          TEXT,
    rl_5h_reset           BIGINT,
    rl_5h_utilization     DOUBLE PRECISION,
    rl_7d_status          TEXT,
    rl_7d_reset           BIGINT,
    rl_7d_utilization     DOUBLE PRECISION,
    rl_representative     TEXT,
    rl_overage_in_use     BIGINT,
    ratelimit_raw         TEXT,
    cost_usd              DOUBLE PRECISION,
    sse_aggregated        BIGINT NOT NULL DEFAULT 0,
    request_id            TEXT,
    upstream_request_id   TEXT,
    proxy                 TEXT,
    simulated             BIGINT NOT NULL DEFAULT 0,
    shape                 TEXT,
    session_id            TEXT,
    error_type            TEXT,
    error_message         TEXT,
    third_party           BIGINT NOT NULL DEFAULT 0,
    rewrites              TEXT,
    device_id_out         TEXT,
    response_excerpt      TEXT,
    sim_reason            TEXT,
    session_key           TEXT,
    session_id_in         TEXT
);
CREATE INDEX idx_usage_logs_frozen_ban ON usage_logs_frozen (ban_event_id, ts);

-- ---------------------------------------------------------------------------
-- 从上游学到的规则
-- ---------------------------------------------------------------------------

-- 形态拒绝 / 已废弃字段 / 零输出请求类 / 拒答过的提示词，见 remember_rejections。
-- 只为重启回填；进程内仍以 HashMap 为准。learned_at 用来做 7 天保鲜。
CREATE TABLE learned_rejections (
    kind       TEXT   NOT NULL,
    model      TEXT   NOT NULL,
    field      TEXT   NOT NULL,
    value      TEXT   NOT NULL DEFAULT '',
    message    TEXT   NOT NULL DEFAULT '',
    learned_at BIGINT NOT NULL DEFAULT unixepoch(),
    reply_sse  BIGINT NOT NULL DEFAULT 0,
    reply_body TEXT   NOT NULL DEFAULT '',
    PRIMARY KEY (kind, model, field, value)
);
