-- 上号 Key（见 store::provision）：只存 sha256，明文只在新建时回一次。
-- pw_tag：建 Key 时所属账号的密码指纹（见 crate::auth::password_tag），密码一变 Key 随即作废。
CREATE TABLE provision_keys (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    label        TEXT   NOT NULL DEFAULT '',
    key_hash     TEXT   NOT NULL UNIQUE,
    key_prefix   TEXT   NOT NULL DEFAULT '',
    disabled     BIGINT NOT NULL DEFAULT 0 CHECK (disabled IN (0, 1)),
    created_at   BIGINT NOT NULL DEFAULT unixepoch(),
    last_used_at BIGINT,
    pw_tag       TEXT   NOT NULL DEFAULT ''
);
CREATE INDEX idx_provision_keys_user ON provision_keys (user_id);
