-- 封号取证待办：停号之后、事件与冻结流水落地之前的那次封号（payload 为 JSON，含当时的账号侧
-- 读数），落地后删掉。两步之间断开时，下一次 record_ban 或后台补做，见 store::bans 的 record_ban。
-- 每次封号各一行：号被重新启用后再被封，不会盖掉上一次没补完的。不随删号删：取证照样要补。
CREATE TABLE ban_pending (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cred_id    BIGINT NOT NULL,
    -- 封号时刻（payload 里也有一份）：裁剪流水时据此留住待办还要冻结的那段窗口。
    ban_ts     BIGINT NOT NULL,
    payload    TEXT   NOT NULL,
    created_at BIGINT NOT NULL DEFAULT unixepoch()
);
CREATE INDEX idx_ban_pending_cred ON ban_pending (cred_id, id);
